name: My Workflow
on:
  push:
    paths:
      - 'nestedActionTest/nestedHelloWorld/**' # Path filter for triggering the workflow only on changes to files in the subdirectory
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Deploy SAM templates
        run: |
          cd nestedActionTest/nestedHelloWorld
          sam deploy --template-file template.yaml --stack-name mystack --capabilities CAPABILITY_IAM --region=eu-west-1
