AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Multi-step component 2

Resources:
  StockTradingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/stock_trader.asl.json
      DefinitionSubstitutions:
        StockCheckerFunctionArn: !ImportValue "microservice1-demo-dev:StockCheckerFunctionArn"
        StockSellerFunctionArn: !ImportValue "microservice1-demo-dev:StockSellerFunctionArn"
        StockBuyerFunctionArn: !ImportValue "microservice1-demo-dev:StockBuyerFunctionArn"
        DDBPutItem: !Sub "arn:${AWS::Partition}:states:::dynamodb:putItem"
        DDBTable: !Ref TransactionTable
      Events:
        HourlyTradingSchedule:
          Type: Schedule
          Properties:
            Description: Schema om de stock trading state machine elk uur uit te voeren
            Enabled: False
            Schedule: rate(1 minute)
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !ImportValue StockCheckerFunctionArn
              - !ImportValue StockSellerFunctionArn
              - !ImportValue StockBuyerFunctionArn
        - DynamoDBWritePolicy:
            TableName: !Ref TransactionTable

  TransactionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
